# gradient-boosted tree: lgb

In [1]:
import pandas as pd

In [2]:
from dataengineers import Dataset

In [3]:
dataset = Dataset('train')
train, test = dataset.build_train_test()

In [4]:
exclude = ['id', 'target', 'delivery_start', 'market']

In [5]:
features = [c for c in train.columns if c not in exclude]

In [6]:
from models import lGBM

In [7]:
lg = lGBM(features)

In [8]:
lg.fit(train, test)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004126 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13728
[LightGBM] [Info] Number of data points in the train set: 106086, number of used features: 65
[LightGBM] [Info] Start training from score 36.843101
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[241]	valid_0's rmse: 47.3643	valid_0's l2: 2243.38

In [9]:
y_vals = lg.predict(test)

In [10]:
from utils import rmse

In [11]:
rmse(test['target'], y_vals)

np.float64(47.36429625575006)

In [12]:
ds2 = Dataset('test')

In [13]:
df_out = ds2.build_main()

In [14]:
y_out = lg.predict(df_out)

In [15]:
df_out['target'] = y_out

In [16]:
df_out.head()

,id,global_horizontal_irradiance,diffuse_horizontal_irradiance,direct_normal_irradiance,cloud_cover_total,cloud_cover_low,cloud_cover_mid,cloud_cover_high,precipitation_amount,visibility,...,residual_lag_6h,residual_lag_12h,residual_lag_24h,residual_lag_48h,residual_rolling_mean_6h,residual_rolling_mean_24h,residual_ramp_1h,residual_ramp_3h,residual_ramp_6h,target
0,133627,0.0,0.0,0.0,100.0,14.0,44.0,100.0,0.0,16600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130.176011
1,133635,0.0,0.0,0.0,100.0,100.0,100.0,88.0,0.0,13800.0,...,NaN,NaN,NaN,NaN,51527.274200,51527.274200,-1463.3271,NaN,NaN,77.935440
2,133643,0.0,0.0,0.0,100.0,70.0,100.0,100.0,0.0,19700.0,...,NaN,NaN,NaN,NaN,50795.610650,50795.610650,-984.5816,NaN,NaN,134.449394
3,133651,0.0,0.0,0.0,99.0,13.0,99.0,94.0,0.0,16200.0,...,NaN,NaN,NaN,NaN,50223.528933,50223.528933,-489.7085,-2937.6172,NaN,131.991870
4,133659,0.0,0.0,0.0,96.0,0.0,96.0,79.0,0.0,14500.0,...,NaN,NaN,NaN,NaN,49815.060950,49815.060950,-121.4928,-1595.7829,NaN,130.391840

In [17]:
from utils import Submission

In [18]:
submit = Submission(df_out)

In [19]:
submit.process()

           id      target
0      133627  130.176011
2183   133629   84.559768
4366   133630   98.407982
10915  133631   85.674663
6549   133633   76.445272
...       ...         ...
4365   146774   45.888244
6548   146775   30.222161
13097  146776   33.430801
8731   146777   34.350939
10914  146778   45.803307

[13098 rows x 2 columns]

In [20]:
submit.validate()

✅ Validation passed!

In [21]:
submit.dump()